import type { LucideIcon, LucideProps } from 'lucide-react';
import { Activity, Archive, ArrowDown, ArrowLeftRight, ArrowUp, ArrowUpDown, Ban, BrainCircuit, CalendarX, Check, ChevronDown, ChevronLeft, ChevronRight, Circle, CircleAlert, CircleCheck, CircleUser, Clock, CornerUpRight, Download, FilePlus, FileSearch, FileText, FileUp, Files, FolderOpen, Gauge, Hash, History, House, Info, Landmark, LayoutDashboard, LayoutGrid, ListChecks, Lock, LogOut, Mail, MailWarning, MailX, Merge, MessageSquare, Network, PanelLeft, Paperclip, Pencil, Plus, Printer, QrCode, Route, Search, Send, ShieldAlert, SlidersHorizontal, Timer, Trash2, Undo2, UserCheck, UserCog, Users, X } from 'lucide-react';

// Trazo de 1,75 y esquinas redondeadas, al estilo de SF Symbols (HIG, Icons): un solo set en todo el sistema (5.3).
function icono(Icono: LucideIcon, tamano: number) {
    const Componente = (props: LucideProps) => <Icono size={tamano} strokeWidth={1.75} aria-hidden {...props} />;
    Componente.displayName = Icono.displayName;

    return Componente;
}

export const IcoAdjunto16 = icono(Paperclip, 16);
export const IcoAgregar = icono(Plus, 18);
export const IcoAgregar16 = icono(Plus, 16);
export const IcoAjustes = icono(SlidersHorizontal, 18);
export const IcoAlerta = icono(CircleAlert, 18);
export const IcoAlerta16 = icono(CircleAlert, 16);
export const IcoAmenaza16 = icono(ShieldAlert, 16);
export const IcoArchivo = icono(Archive, 18);
export const IcoArchivo16 = icono(Archive, 16);
export const IcoAreas = icono(Network, 18);
export const IcoBuscar = icono(Search, 18);
export const IcoBuscarDocumento16 = icono(FileSearch, 16);
export const IcoCandado = icono(Lock, 18);
export const IcoCandado16 = icono(Lock, 16);
export const IcoCerrar = icono(X, 18);
export const IcoCerrar12 = icono(X, 12);
export const IcoCerrar16 = icono(X, 16);
export const IcoCheck16 = icono(Check, 16);
export const IcoCirculo16 = icono(Circle, 16);
export const IcoColas = icono(Activity, 18);
export const IcoComentario = icono(MessageSquare, 18);
export const IcoComponentes = icono(LayoutGrid, 18);
export const IcoCorrecto = icono(CircleCheck, 18);
export const IcoCorrecto16 = icono(CircleCheck, 16);
export const IcoCorreo = icono(Mail, 18);
export const IcoCorreoAviso = icono(MailWarning, 18);
export const IcoCorreoBloqueado = icono(MailX, 18);
export const IcoDerivar = icono(CornerUpRight, 18);
export const IcoDerivar16 = icono(CornerUpRight, 16);
export const IcoDescargar = icono(Download, 18);
export const IcoDescargar16 = icono(Download, 16);
export const IcoDeshacer = icono(Undo2, 18);
export const IcoDocumento = icono(FileText, 18);
export const IcoDocumentos = icono(Files, 18);
export const IcoEditar = icono(Pencil, 18);
export const IcoEliminar = icono(Trash2, 18);
export const IcoEnviar = icono(Send, 18);
export const IcoExpedientes = icono(FolderOpen, 18);
export const IcoFeriado = icono(CalendarX, 18);
export const IcoFlechaAbajo16 = icono(ChevronDown, 16);
export const IcoFlechaDerecha16 = icono(ChevronRight, 16);
export const IcoFlechaIzquierda16 = icono(ChevronLeft, 16);
export const IcoFusionar = icono(Merge, 18);
export const IcoHistorial16 = icono(History, 16);
export const IcoIa = icono(BrainCircuit, 18);
export const IcoImprimir = icono(Printer, 18);
export const IcoInfo = icono(Info, 18);
export const IcoInicio = icono(House, 18);
export const IcoInstitucion = icono(Landmark, 18);
export const IcoInstrucciones = icono(ListChecks, 18);
export const IcoIntercambiar = icono(ArrowLeftRight, 18);
export const IcoNuevoDocumento = icono(FilePlus, 18);
export const IcoNumeral = icono(Hash, 18);
export const IcoOrdenAsc16 = icono(ArrowUp, 16);
export const IcoOrdenDesc16 = icono(ArrowDown, 16);
export const IcoOrdenar16 = icono(ArrowUpDown, 16);
export const IcoPanelLateral = icono(PanelLeft, 18);
export const IcoPersona = icono(CircleUser, 18);
export const IcoPlazo = icono(Timer, 18);
export const IcoProhibido = icono(Ban, 18);
export const IcoProhibido16 = icono(Ban, 16);
export const IcoQr = icono(QrCode, 18);
export const IcoReloj16 = icono(Clock, 16);
export const IcoResponsables = icono(UserCog, 18);
export const IcoRuta = icono(Route, 18);
export const IcoSalir = icono(LogOut, 18);
export const IcoSubirDocumento = icono(FileUp, 18);
export const IcoTablero = icono(LayoutDashboard, 18);
export const IcoTomar = icono(UserCheck, 18);
export const IcoUsuarios = icono(Users, 18);
export const IcoVelocimetro = icono(Gauge, 18);
